### ISSUE TITLE
Validating email with TLD minimum length of 2 chars

### ISSUE THREAD

**Issue by LM450N** [PolymerElements/gold-email-input#20]
It's a kind of __proposal__. Until now, no [TLD][1] of one char was accepted. Would it be a good idea to update the RegExp to check emails who end with minimum 2 chars :question: 

[1]: https://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by notwaldorf** [comment]
Hmmm, I'm not sure what you mean. In the demo, `batman@na.na` is a valid email. Do you mean that `batman@na.n` should be as well? I don't see a 1 letter TLD in the link you sent (but it's likely that I missed it), so I'd rather cross that bridge when we get there

We're using the official spec regex (http://www.w3.org/TR/html-markup/input.email.html#input.email.attrs.value.single), so I would imagine that would get updated when the 1 letter TLDs are allowed

**Comment by LM450N** [comment]
I mean, the RegExp currently used allows already the email with a TLD of 1 letter (because it's already allowed by the [RFC-1123](https://www.ietf.org/rfc/rfc1123.txt) section 2.1).

![image](https://cloud.githubusercontent.com/assets/2325091/8601342/c8503dfe-266b-11e5-8415-9f2205672c56.png)

In fact, I would propose to not allow an email with a TLD of 1. :confused: 

The reason is the plus symbol in the RegExp:

    ^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$

I think it could be replaced by:

    ^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*[a-zA-Z0-9-]{2,}$

I'm not sure about my example. Someone must check it.

**Comment by notwaldorf** [comment]
Closing this, as well as the corresponding PR https://github.com/PolymerElements/gold-email-input/pull/22: 
I'd like to keep the default regex the one specified in the spec (which allows single letter tlds), and not add custom bits to it. In your usage of the element, you can override the regex property, if you wish.

**Comment by LM450N** [comment]
Got it!
