### ISSUE TITLE
Unit tests not pass because of the IronFormElementBehavior

### ISSUE THREAD

**Issue by LM450N** [PolymerElements/gold-email-input#21]
The unit tests are not passing. The encountered error is __this._parentForm.fire is not a function__.

![image](https://cloud.githubusercontent.com/assets/2325091/8605288/86a99e2c-2684-11e5-903d-cb1a9e7c5ea9.png)

The reason is the _inheritance_ of the [Polymer.IronFormElementBehavior](https://github.com/PolymerElements/iron-form-element-behavior/blob/master/iron-form-element-behavior.html#L70).

I removed it and all the unit tests was successful. :ok: 

PS: Sorry for the term _inheritance_, I come from the Java world.

**Comment by LM450N** [comment]
It will solved with the PR https://github.com/PolymerElements/iron-form-element-behavior/pull/10

**Comment by notwaldorf** [comment]
Fixed long ago! :)
