### ISSUE TITLE
stop capitalisation

### ISSUE THREAD

**Issue by MrAntix** [PolymerElements/gold-email-input#34]
added autocapitalize="none" as emails never need to be capitalized

      <input is="iron-input" id="input"
        ...
          autocapitalize="none"
         >

this does assume that no one wants capitals, could make it optional

          autocapitalize$="[[autocapitalize]]"

I've committed a change to my fork, if you want it, but I guess its easy enough to add in the next round

MrAntix/gold-email-input@082e09e045ea526249f60959087bfadc26a3c185

**Comment by notwaldorf** [comment]
@MrAntix Oh thanks! That makes sense. Do you want to send a PR to this repo? I can just add it myself if you don't want to/have time :)

**Comment by MrAntix** [comment]
glad to, here you go #35

**Comment by notwaldorf** [comment]
Fixed in 0c71935
