### ISSUE TITLE
style not working

### ISSUE THREAD

**Issue by HedCET** [PolymerElements/gold-email-input#39]
i tried this
```
<style is="custom-style">
gold-email-input {
    --paper-input-container-color: white!important;
    --paper-input-container-focus-color: white!important;
    --paper-input-container-invalid-color: white!important;
    --paper-input-container-input-color: white!important;
}
</style>
```
but not working inside body tag, but working perfectly inside dom-module

**Comment by notwaldorf** [comment]
I can't repro this. Here's a jsbin that does just that: http://jsbin.com/hefute/edit?html,output
and looks like this:
<img width="273" alt="screen shot 2015-10-19 at 5 44 11 pm" src="https://cloud.githubusercontent.com/assets/1369170/10595095/072ed70c-7689-11e5-88c3-9cf4f266cc8e.png">

Please re-open if you can repro :)
