### ISSUE TITLE
test broken: done() called multiple times

### ISSUE THREAD

**Issue by StephenTurley** [PolymerElements/gold-email-input#49]
```
<gold-email-input name="email" label="Email Address" on-value-changed="_emailChanged" auto-validate required></gold-email-input>

it('should reset to default message on change', function(done){
            emailField.errorMessage = "foo";
            
            emailField.addEventListener('value-changed', function(e){
              expect(emailField.errorMessage).to.equal(defaultErrorMsg);
              done(); 
            });
            
            emailField.value = 'a';
});
```

The following test fails for:

done() called multiple times
  Suite.<anonymous> at signup-form-test.html:42
  Suite.<anonymous> at signup-form-test.html:27
  Suite.<anonymous> at signup-form-test.html:25

**Comment by notwaldorf** [comment]
I think this needs a fix similar to https://github.com/PolymerElements/gold-cc-input/issues/38 (check the change in the test section, not the feature being added 😄 ). Would you be interested in sending a PR to fix this?

**Comment by StephenTurley** [comment]
I've looked at it and the fix wasn't obvious to me. I'll give it another shot this weekend though. Please don't let this comment prevent someone more familiar with it from taking a look though.

**Comment by StephenTurley** [comment]
So the fix linked is for a test. It seems strange that the elements are firing events multiple times. I could edit all of my unit tests to check for this but it seems like a work around rather than a solution. The real issue is that the events are being fired more than once.
