### ISSUE TITLE
Move <script> inside <dom-module>

### ISSUE THREAD

**Issue by cherukumilli** [PolymerElements/gold-email-input#52]
This elements code is not following the same standards as other elements. This elements javascript code is outside the <dom-module> </dom-module>. All other elements have javascript code inside the <dom-module> </dom-module> tags

### Current code:
```
...
<dom-module>
   ...
</dom-module>
<script>
   ...
</script>
```

### Expected:
```
...
<dom-module>
   ...
   <script>
      ...
   </script>
</dom-module>
```

A similar issue has been fixed for other elements like paper-fab. Please check https://github.com/PolymerElements/paper-fab/pull/53 for details.

**Comment by notwaldorf** [comment]
Hi! Thanks for pointing this out! Would you be interested in sending a PR for that? 😻

**Comment by notwaldorf** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by notwaldorf** [comment]
Fixed in https://github.com/PolymerElements/gold-email-input/pull/53
