### ISSUE TITLE
gold-email-input does not fire the 'change' event

### ISSUE THREAD

**Issue by Claudio-DC** [PolymerElements/gold-email-input#57]
In the definition file (gold-email-input.html) is absent:

on-change="_onChange"

Thanks

**Comment by notwaldorf** [comment]
Cannot reproduce: http://jsbin.com/tupaga/edit?html,console,output. The 'change' event is fired correctly. 

The `change` event comes from `PaperInputBehavior`, so while you will not see it in the html file directly, you can see it in the element's aggregated [docs](https://elements.polymer-project.org/elements/gold-email-input) (scroll to the bottom, to the "Events" section)
