### ISSUE TITLE
:host { display: block; } overrides hidden attribute

### ISSUE THREAD

**Issue by trevordixon** [PolymerElements/gold-email-input#64]
The hidden attribute (https://developer.mozilla.org/en/docs/Web/HTML/Global_attributes/hidden) fails to hide a gold-email-input because of `:host { display: block; }`. Should this and other elements include `:host([hidden]) { display: none; }` to preserve the correct behavior?

**Comment by notwaldorf** [comment]
Yes, that is correct. You can see that [some elements](https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L81) already have this style.

Would you be interested in sending a PR to fix this?
