### ISSUE TITLE
Polymer 2.0

### ISSUE THREAD

**Issue by honzabenes** [PolymerElements/gold-email-input#72]
I am stuck on Polymer 1 because of this dependency. Would really love to see an update. Thanks

**Comment by xueyio** [comment]
@honzabenes same for me. I'm also stuck on this before upgrading to Polymer 2.0. It would be lovely to see it got updated.

**Comment by cordovapolymer** [comment]
@notwaldorf any updates on this?

**Comment by ShaggyDude** [comment]
I need this as well.

**Comment by aruntk** [comment]
@honzabenes I've submitted a PR https://github.com/PolymerElements/gold-email-input/pull/73. Meanwhile you can use https://github.com/aruntk/gold-email-input/releases/tag/2.0.0. :)

**Comment by robrez** [comment]
I was interested on the 2.0 version, too. But after looking more, I'm wondering if this element is really needed.

Reading the code:
```
       /**
         * The regular expression used to validate the email. By default, the
         * input is of type=email and uses the native input regex, as defined in
         * the spec: http://www.w3.org/TR/html-markup/input.email.html#input.email.attrs.value.single.
         * You can override this if you want your email to be validated against
         * a custom regex. If the empty string, then no validation will be applied.
         */
        regex: {
          type: String,
          value: null
        },
```

I just replaced my usage with something like:
```
  <paper-input type="email"></paper-input>
```

And it worked okay for my needs. If you _were_ actually overriding with a regex... paper-input supports regex.

Is there anything I'm missing?

**Comment by davidmaxwaterman** [comment]
The url in the code doesn't seem to work, but I found this one:

https://www.w3.org/TR/2012/WD-html-markup-20121025/input.email.html

Also, in case anyone was wondering:

http://caniuse.com/#feat=input-email-tel-url

So, I am also wondering if this element is now redundant.

**Comment by notwaldorf** [comment]
This element has always been redundant, in my opinion. As @robrez commented, it's exactly equivalent to a `<paper-input type="email">`. In the early days of the Polymer 1 elements we had received a request to just move that into its own element, but you're right, I am not sure it's worth it.

@e111077 What do you think about deprecating and just adding a note to the readme that this should just be replaced by a paper-input?
